# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0002_auto_20180601_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='retail_warehouse',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
