# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0003_retail_warehouse_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retail_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('domain', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('item_type', models.CharField(max_length=20)),
                ('delivery_time', models.CharField(max_length=40)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.Retail_Warehouse')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='retail_product',
            unique_together=set([('warehouse', 'product_name')]),
        ),
    ]
