# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0004_auto_20180601_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retail_product',
            old_name='product_name',
            new_name='product_title',
        ),
        migrations.AlterField(
            model_name='retail_product',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='retail_product',
            unique_together=set([('warehouse', 'product_title')]),
        ),
    ]
