# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0005_auto_20180601_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='retail_product',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
