# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0006_retail_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retail_product',
            name='item_type',
        ),
    ]
