# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 20:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0007_remove_retail_product_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='retail_product',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
